# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagegaleria', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegaleria.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagegaleria.Location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
